version: "3.6"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      #cert for domain
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.delayBeforeCheck=60s"

      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.disablePropagationCheck=true"
      #put email here
      - "--certificatesresolvers.letsencrypt.acme.email=your email here"

      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      #server for certs
      #https://acme-staging-v02.api.letsencrypt.org/directory is for testing if it works
      #https://acme-v02.api.letsencrypt.org/directory for real cert
      - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      #good bits for proxy
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certResolver=letsencrypt"
      #change here
      - "--entrypoints.websecure.http.tls.domains[0].main=domain.tech"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.domain.tech"

    #put cf credentials
    environment:
      - CF_DNS_API_TOKEN=cf token here
      - CF_API_EMAIL=cf email
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/letsencrypt
    labels:
      #exopose trafik homepage WARNING no password but since its local it be alright
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`proxy.yourdomain.tech`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.tls=true"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=letsencrypt"
    networks:
    #for web app
      - frontend
    #for database
      - backend
      - traefik_default

networks:
  frontend:
    external: true
  backend:
    external: true
  traefik_default:
    external: true
